# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85846c6b08d94d43af368fe6f4da6bab5e47b25116b59c6dfde95e51b7765270fc1d062f00a05213877a10955302ac2cd77491cbd55576ed4da22f3642c77e18

test:
  secret_key_base: 6d091cde97a777e5d7be8af938ecbe040c486308479d8059ab1653879b617df058aaa0009ea193d707fb7407baa7471f17894d23f76e674335ae87bc15be5797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
